"""
Training configuration file
"""

# Data configuration - Fixed paths for local training
DATA_CONFIG = {
    'data_dir': '/home/grace_chen/data',  # Base data directory (contains json/ and images/)
    'image_dir': '/home/grace_chen/data/images',  # Images directory
    'max_samples_per_file': None,  # None = use all data, int = limit samples per file
    'compatibility_threshold': 1,  # Compatibility matching threshold (lowered for more data)
    'max_compatible_items': 5,  # Maximum compatible items per product (increased for diversity)
    
    # GCP Storage configuration
    'use_gcp_storage': False,  # Set to True when training on GCP
    'gcp_bucket_name': 'styleme-data-bucket',
    'gcp_project_id': 'styleme-475201',
    'gcp_data_prefix': 'data/',  # Prefix for data files in bucket
    'gcp_images_prefix': 'images/',  # Prefix for images in bucket
}

# Training configuration - Optimized for 75% target accuracy
TRAINING_CONFIG = {
    'batch_size': 16,  # Batch size (reduced for better gradient updates, matching EXP_002)
    'epochs': 30,  # Number of training epochs (increased from 20 but not too high)
    'learning_rate': 1e-5,  # Learning rate (keep same as successful EXP_002)
    'num_workers': 2,  # Number of data loading worker processes
    'patience': 8,  # Early stopping patience (increased to allow more training)
    'target_accuracy': 0.75,  # Target accuracy (matching successful EXP_002)
}

# Model configuration
MODEL_CONFIG = {
    'model_name': 'openai/clip-vit-base-patch32',
    'freeze_layers': 8,  # Number of frozen layers
    'feature_dim': 512,  # Feature dimension
}

# Triplet Loss configuration - Optimized for better separation
TRIPLET_CONFIG = {
    'margin': 0.7,  # Triplet Loss margin (increased for better feature separation)
    'distance_metric': 'euclidean',  # Distance metric
}

# Optimizer configuration - Optimized for better convergence
OPTIMIZER_CONFIG = {
    'optimizer': 'AdamW',
    'weight_decay': 0.005,  # Reduced weight decay for less regularization
    'scheduler': 'CosineAnnealingLR',
}

# Save configuration - Will be auto-generated by training script
SAVE_CONFIG = {
    'save_dir': 'temp_training_output',  # Temporary directory, will be moved to experiments/
    'save_best': True,
    'save_final': True,
    'save_history': True,
    'save_plots': True,
}

# Evaluation configuration
EVALUATION_CONFIG = {
    'eval_batches': 20,  # Number of batches for quick evaluation
    'full_eval_batches': 100,  # Number of batches for full evaluation
    'recommendation_k': 5,  # Number of recommendations
}
