"""
Training configuration file
"""

# Data configuration - GCS configuration
DATA_CONFIG = {
    'gcp_bucket_name': 'styleme-data-bucket',  # GCS bucket name
    'gcp_project_id': 'styleme-475201',  # GCP project ID
    'data_prefix': 'json',  # JSON data prefix in GCS (actual structure)
    'images_prefix': 'images',  # Images prefix in GCS (actual structure)
    'max_samples_per_file': None,  # None = use all data, int = limit samples per file
    'compatibility_threshold': 1,  # Compatibility matching threshold (lowered for more data)
    'max_compatible_items': 5,  # Maximum compatible items per product (increased for diversity)
}

# Training configuration - Optimized for GPU training with parallel loading
TRAINING_CONFIG = {
    'batch_size': 32,  # Larger batch size for GPU training
    'epochs': 20,  # Training epochs
    'learning_rate': 5e-6,  # Learning rate
    'num_workers': 4,  # Multi-threaded data loading (enabled for parallel loading)
    'patience': 10,  # Early stopping patience
    'target_accuracy': 0.85,  # Target accuracy
}

# Model configuration
MODEL_CONFIG = {
    'model_name': 'openai/clip-vit-base-patch32',
    'freeze_layers': 8,  # Number of frozen layers
    'feature_dim': 512,  # Feature dimension
}

# Triplet Loss configuration - Optimized for better separation
TRIPLET_CONFIG = {
    'margin': 0.7,  # Triplet Loss margin (increased for better feature separation)
    'distance_metric': 'euclidean',  # Distance metric
}

# Optimizer configuration - Optimized for better convergence
OPTIMIZER_CONFIG = {
    'optimizer': 'AdamW',
    'weight_decay': 0.005,  # Reduced weight decay for less regularization
    'scheduler': 'CosineAnnealingLR',
}

# Save configuration - Will be auto-generated by training script
SAVE_CONFIG = {
    'save_dir': 'temp_training_output',  # Temporary directory, will be moved to experiments/
    'save_best': True,
    'save_final': True,
    'save_history': True,
    'save_plots': True,
}

# Evaluation configuration
EVALUATION_CONFIG = {
    'eval_batches': 20,  # Number of batches for quick evaluation
    'full_eval_batches': 100,  # Number of batches for full evaluation
    'recommendation_k': 5,  # Number of recommendations
}
